### ISSUE TITLE
bi-encoder jskit unit tests not working

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#129]
The unit tests for biencoder jskit are not working on main.  To reproduce, run

```
cd jskit/encoders/
python3 -m unittest tests.test_biencoder
```
and see the following failure:
```
Time: 0.009 - test_biencoder_context_emb: [failed]
FTime: 0.006 - test_biencoder_infer: [failed]
FTime: 0.005 - test_biencoder_train: [failed]
FTruncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/home/ypkang/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:2251: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
Time: 0.059 - test_candidate_embedding: [failed]
ETime: 0.006 - test_cos_sim_function: [failed]
F
======================================================================
ERROR: test_candidate_embedding (tests.test_biencoder.biencoder_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ypkang/projects/jaseci/jskit/encoders/tests/test_biencoder.py", line 78, in test_candidate_embedding
    len(response.json()[0][0]),
TypeError: 'float' object is not subscriptable

======================================================================
FAIL: test_biencoder_context_emb (tests.test_biencoder.biencoder_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ypkang/projects/jaseci/jskit/encoders/tests/test_biencoder.py", line 65, in test_biencoder_context_emb
    self.assertEqual(response.status_code, 200)
AssertionError: 422 != 200

======================================================================
FAIL: test_biencoder_infer (tests.test_biencoder.biencoder_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ypkang/projects/jaseci/jskit/encoders/tests/test_biencoder.py", line 54, in test_biencoder_infer
    self.assertEqual(response.status_code, 200)
AssertionError: 422 != 200

======================================================================
FAIL: test_biencoder_train (tests.test_biencoder.biencoder_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ypkang/projects/jaseci/jskit/encoders/tests/test_biencoder.py", line 43, in test_biencoder_train
    self.assertEqual(response.status_code, 200)
AssertionError: 422 != 200

======================================================================
FAIL: test_cos_sim_function (tests.test_biencoder.biencoder_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ypkang/projects/jaseci/jskit/encoders/tests/test_biencoder.py", line 32, in test_cos_sim_function
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 5 tests in 0.086s

FAILED (failures=4, errors=1)
```

**Comment by ypkang** [comment]
@AshishMahendra could you take a look at this when you get a chance?

**Comment by AshishMahendra** [comment]
> @AshishMahendra could you take a look at this when you get a chance?

Updated the test data structures
